/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.awt.Color;
import java.text.SimpleDateFormat;
import javax.swing.*;
import java.util.Calendar;
import java.util.Collections;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Mahmudul Hasan
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        SimpleDateFormat timeformat=new SimpleDateFormat("EEE, MMM d, ''yyyy");
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        jLabel13.setText(timeformat.format(Calendar.getInstance().getTime()));
        hideNav();
    }
    
    //UI Codes
    void hideNav(){
        jLabel58.setVisible(false);
        jComboBox6.setVisible(false);
        jButton23.setVisible(false);
        jButton24.setVisible(false);
        jButton25.setVisible(false);
        jButton29.setVisible(false);
    }
        
    void showNav(String title){
        jLabel58.setText(title);
        jLabel58.setVisible(true);
        jComboBox6.setVisible(true);
        jButton23.setVisible(true);
        jButton24.setVisible(true);
        jButton25.setVisible(true);
        jButton29.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        menu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        menu2 = new javax.swing.JMenu();
        test3 = new javax.swing.JMenuItem();
        mainPanel = new javax.swing.JPanel();
        topPanel = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jButton29 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jLabel58 = new javax.swing.JLabel();
        jComboBox6 = new javax.swing.JComboBox<>();
        SidePanel = new javax.swing.JPanel();
        home = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        home1 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        home2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        home3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        home4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        home5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        home6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        home7 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        home8 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        home9 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        Container = new javax.swing.JLayeredPane();
        homePanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel45 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel46 = new javax.swing.JLabel();
        memberPanel = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton6 = new javax.swing.JButton();
        accountsPanel = new javax.swing.JPanel();
        collectionPanel = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jComboBox3 = new javax.swing.JComboBox<>();
        jButton30 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        donationPanel = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable6 = new javax.swing.JTable();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        jComboBox4 = new javax.swing.JComboBox<>();
        jButton31 = new javax.swing.JButton();
        expensesPanel = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTable7 = new javax.swing.JTable();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jTextField5 = new javax.swing.JTextField();
        jComboBox5 = new javax.swing.JComboBox<>();
        salaryPanel = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTable8 = new javax.swing.JTable();
        jButton7 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton28 = new javax.swing.JButton();
        comitteePanel = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        adminPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        menu1.setText("Test");

        jMenuItem1.setText("test");
        menu1.add(jMenuItem1);

        jPopupMenu1.add(menu1);

        menu2.setText("jMenu4");

        test3.setText("jMenuItem3");
        menu2.add(test3);

        jPopupMenu1.add(menu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        mainPanel.setLayout(null);

        topPanel.setBackground(new java.awt.Color(255, 255, 255));
        topPanel.setLayout(null);

        jPanel14.setBackground(new java.awt.Color(51, 51, 51));
        topPanel.add(jPanel14);
        jPanel14.setBounds(1140, 0, 100, 110);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Admin, Developer");
        jLabel14.setAlignmentX(931.0F);
        jLabel14.setAlignmentY(64.0F);
        topPanel.add(jLabel14);
        jLabel14.setBounds(930, 70, 150, 30);

        jLabel37.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(0, 0, 0));
        jLabel37.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel37.setText("Mahmudu Hasan Shafin");
        jLabel37.setAlignmentX(931.0F);
        jLabel37.setAlignmentY(64.0F);
        topPanel.add(jLabel37);
        jLabel37.setBounds(930, 40, 200, 30);

        jLabel38.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(0, 0, 0));
        jLabel38.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel38.setText("Welcome");
        jLabel38.setAlignmentX(931.0F);
        jLabel38.setAlignmentY(64.0F);
        topPanel.add(jLabel38);
        jLabel38.setBounds(920, 0, 100, 50);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("19 May 2021");
        jLabel13.setAlignmentX(931.0F);
        jLabel13.setAlignmentY(64.0F);
        topPanel.add(jLabel13);
        jLabel13.setBounds(740, 0, 180, 40);

        jLabel47.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(0, 0, 0));
        jLabel47.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel47.setText("Baitul Aman Jame Masjid, Feni");
        jLabel47.setAlignmentX(931.0F);
        jLabel47.setAlignmentY(64.0F);
        topPanel.add(jLabel47);
        jLabel47.setBounds(420, 0, 270, 40);

        jLabel57.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel57.setForeground(new java.awt.Color(0, 0, 0));
        jLabel57.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel57.setText("HOME");
        jLabel57.setAlignmentX(931.0F);
        jLabel57.setAlignmentY(64.0F);
        topPanel.add(jLabel57);
        jLabel57.setBounds(10, 0, 270, 40);

        jButton29.setText("LAST");
        jButton29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton29ActionPerformed(evt);
            }
        });
        topPanel.add(jButton29);
        jButton29.setBounds(660, 90, 70, 30);

        jButton25.setText("FIRST");
        topPanel.add(jButton25);
        jButton25.setBounds(590, 90, 70, 30);

        jButton24.setText("NEXT");
        topPanel.add(jButton24);
        jButton24.setBounds(520, 90, 70, 30);

        jButton23.setText("PREVIOUS");
        topPanel.add(jButton23);
        jButton23.setBounds(430, 90, 90, 30);

        jLabel58.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel58.setForeground(new java.awt.Color(0, 0, 0));
        jLabel58.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel58.setText("Member:");
        jLabel58.setAlignmentX(931.0F);
        jLabel58.setAlignmentY(64.0F);
        topPanel.add(jLabel58);
        jLabel58.setBounds(0, 90, 150, 30);

        topPanel.add(jComboBox6);
        jComboBox6.setBounds(150, 90, 280, 30);

        mainPanel.add(topPanel);
        topPanel.setBounds(120, 0, 1250, 120);

        SidePanel.setBackground(new java.awt.Color(0, 51, 102));
        SidePanel.setLayout(null);

        home.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Accounts");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        home.add(jLabel1);
        jLabel1.setBounds(0, 0, 100, 50);

        SidePanel.add(home);
        home.setBounds(10, 130, 100, 50);

        home1.setLayout(null);

        jLabel16.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Home");
        jLabel16.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentRemoved(java.awt.event.ContainerEvent evt) {
                jLabel16ComponentRemoved(evt);
            }
        });
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel16MouseEntered(evt);
            }
        });
        home1.add(jLabel16);
        jLabel16.setBounds(0, 0, 100, 50);

        SidePanel.add(home1);
        home1.setBounds(10, 70, 100, 50);

        home2.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Members");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        home2.add(jLabel3);
        jLabel3.setBounds(0, 0, 100, 50);

        SidePanel.add(home2);
        home2.setBounds(10, 190, 100, 50);

        home3.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Collections");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        home3.add(jLabel4);
        jLabel4.setBounds(0, 0, 100, 50);

        SidePanel.add(home3);
        home3.setBounds(10, 250, 100, 50);

        home4.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Expenses");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        home4.add(jLabel5);
        jLabel5.setBounds(0, 0, 100, 50);

        SidePanel.add(home4);
        home4.setBounds(10, 370, 100, 50);

        home5.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Donations");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        home5.add(jLabel6);
        jLabel6.setBounds(0, 0, 100, 50);

        SidePanel.add(home5);
        home5.setBounds(10, 310, 100, 50);

        home6.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Salary");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        home6.add(jLabel7);
        jLabel7.setBounds(0, 0, 100, 50);

        SidePanel.add(home6);
        home6.setBounds(10, 430, 100, 50);

        home7.setLayout(null);

        jLabel8.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Comittee");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        home7.add(jLabel8);
        jLabel8.setBounds(0, 0, 100, 50);

        SidePanel.add(home7);
        home7.setBounds(10, 490, 100, 50);

        home8.setLayout(null);

        jLabel9.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Admin");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        home8.add(jLabel9);
        jLabel9.setBounds(0, 0, 100, 50);

        SidePanel.add(home8);
        home8.setBounds(10, 550, 100, 50);

        home9.setLayout(null);

        jLabel10.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Logout");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        home9.add(jLabel10);
        jLabel10.setBounds(0, 0, 100, 50);

        SidePanel.add(home9);
        home9.setBounds(10, 610, 100, 50);

        jPanel2.setBackground(new java.awt.Color(0, 51, 102));
        jPanel2.setLayout(null);

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/asset-1.png"))); // NOI18N
        jLabel11.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentRemoved(java.awt.event.ContainerEvent evt) {
                jLabel11ComponentRemoved(evt);
            }
        });
        jPanel2.add(jLabel11);
        jLabel11.setBounds(0, 0, 120, 60);

        SidePanel.add(jPanel2);
        jPanel2.setBounds(0, 0, 120, 60);

        mainPanel.add(SidePanel);
        SidePanel.setBounds(0, 0, 120, 768);

        Container.setBackground(new java.awt.Color(0, 0, 51));
        Container.setLayout(new java.awt.CardLayout());

        homePanel.setBackground(new java.awt.Color(255, 255, 255));
        homePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                homePanelMouseReleased(evt);
            }
        });
        homePanel.setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Name", "Amount"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        homePanel.add(jScrollPane1);
        jScrollPane1.setBounds(10, 270, 370, 210);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Name", "Amount"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        homePanel.add(jScrollPane2);
        jScrollPane2.setBounds(410, 270, 370, 210);

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Recent Expenses");
        jLabel18.setAlignmentX(931.0F);
        jLabel18.setAlignmentY(64.0F);
        homePanel.add(jLabel18);
        jLabel18.setBounds(470, 220, 240, 40);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Name", "Amount"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        homePanel.add(jScrollPane3);
        jScrollPane3.setBounds(810, 270, 370, 210);

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Recent Members");
        jLabel20.setAlignmentX(931.0F);
        jLabel20.setAlignmentY(64.0F);
        homePanel.add(jLabel20);
        jLabel20.setBounds(860, 220, 240, 40);

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Recent Donation");
        jLabel21.setAlignmentX(931.0F);
        jLabel21.setAlignmentY(64.0F);
        homePanel.add(jLabel21);
        jLabel21.setBounds(50, 220, 240, 40);

        jPanel6.setLayout(null);

        jLabel29.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(0, 0, 0));
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("Bank");
        jLabel29.setAlignmentX(931.0F);
        jLabel29.setAlignmentY(64.0F);
        jPanel6.add(jLabel29);
        jLabel29.setBounds(10, 0, 240, 40);

        jLabel30.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(0, 0, 0));
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("3002");
        jLabel30.setAlignmentX(931.0F);
        jLabel30.setAlignmentY(64.0F);
        jPanel6.add(jLabel30);
        jLabel30.setBounds(10, 40, 240, 40);

        homePanel.add(jPanel6);
        jPanel6.setBounds(290, 10, 270, 90);

        jPanel5.setLayout(null);

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 0, 0));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Expenses this week");
        jLabel23.setAlignmentX(931.0F);
        jLabel23.setAlignmentY(64.0F);
        jPanel5.add(jLabel23);
        jLabel23.setBounds(10, 0, 240, 40);

        jLabel26.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 0, 0));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("3002");
        jLabel26.setAlignmentX(931.0F);
        jLabel26.setAlignmentY(64.0F);
        jPanel5.add(jLabel26);
        jLabel26.setBounds(10, 40, 240, 40);

        homePanel.add(jPanel5);
        jPanel5.setBounds(10, 110, 270, 90);

        jPanel4.setLayout(null);

        jLabel27.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 0, 0));
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("Income-this week");
        jLabel27.setAlignmentX(931.0F);
        jLabel27.setAlignmentY(64.0F);
        jPanel4.add(jLabel27);
        jLabel27.setBounds(10, 0, 240, 40);

        jLabel28.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 0, 0));
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("3002");
        jLabel28.setAlignmentX(931.0F);
        jLabel28.setAlignmentY(64.0F);
        jPanel4.add(jLabel28);
        jLabel28.setBounds(10, 30, 240, 40);

        homePanel.add(jPanel4);
        jPanel4.setBounds(10, 10, 270, 90);

        jPanel7.setLayout(null);

        jLabel31.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(0, 0, 0));
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setText("Khadim");
        jLabel31.setAlignmentX(931.0F);
        jLabel31.setAlignmentY(64.0F);
        jPanel7.add(jLabel31);
        jLabel31.setBounds(220, 0, 120, 40);

        jLabel32.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(0, 0, 0));
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setText("10");
        jLabel32.setAlignmentX(931.0F);
        jLabel32.setAlignmentY(64.0F);
        jPanel7.add(jLabel32);
        jLabel32.setBounds(240, 40, 90, 40);

        jLabel39.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(0, 0, 0));
        jLabel39.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel39.setText("Imam");
        jLabel39.setAlignmentX(931.0F);
        jLabel39.setAlignmentY(64.0F);
        jPanel7.add(jLabel39);
        jLabel39.setBounds(0, 0, 80, 40);

        jLabel40.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(0, 0, 0));
        jLabel40.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel40.setText("Muwajjin");
        jLabel40.setAlignmentX(931.0F);
        jLabel40.setAlignmentY(64.0F);
        jPanel7.add(jLabel40);
        jLabel40.setBounds(90, 0, 120, 40);

        jLabel41.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(0, 0, 0));
        jLabel41.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel41.setText("3");
        jLabel41.setAlignmentX(931.0F);
        jLabel41.setAlignmentY(64.0F);
        jPanel7.add(jLabel41);
        jLabel41.setBounds(10, 40, 90, 40);

        jLabel42.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(0, 0, 0));
        jLabel42.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel42.setText("5");
        jLabel42.setAlignmentX(931.0F);
        jLabel42.setAlignmentY(64.0F);
        jPanel7.add(jLabel42);
        jLabel42.setBounds(120, 40, 90, 40);

        homePanel.add(jPanel7);
        jPanel7.setBounds(850, 10, 350, 190);

        jPanel8.setLayout(null);

        jLabel33.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(0, 0, 0));
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel33.setText("Cash");
        jLabel33.setAlignmentX(931.0F);
        jLabel33.setAlignmentY(64.0F);
        jPanel8.add(jLabel33);
        jLabel33.setBounds(10, 0, 240, 40);

        jLabel34.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(0, 0, 0));
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel34.setText("3002");
        jLabel34.setAlignmentX(931.0F);
        jLabel34.setAlignmentY(64.0F);
        jPanel8.add(jLabel34);
        jLabel34.setBounds(10, 30, 240, 40);

        homePanel.add(jPanel8);
        jPanel8.setBounds(290, 110, 270, 90);

        jPanel9.setLayout(null);

        jLabel35.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(0, 0, 0));
        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel35.setText("Total Members");
        jLabel35.setAlignmentX(931.0F);
        jLabel35.setAlignmentY(64.0F);
        jPanel9.add(jLabel35);
        jLabel35.setBounds(10, 0, 240, 40);

        jLabel36.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(0, 0, 0));
        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel36.setText("3002");
        jLabel36.setAlignmentX(931.0F);
        jLabel36.setAlignmentY(64.0F);
        jPanel9.add(jLabel36);
        jLabel36.setBounds(10, 40, 240, 40);

        homePanel.add(jPanel9);
        jPanel9.setBounds(570, 10, 270, 90);

        jPanel10.setLayout(null);

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 0, 0));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("Total: 20202");
        jLabel24.setAlignmentX(931.0F);
        jLabel24.setAlignmentY(64.0F);
        jPanel10.add(jLabel24);
        jLabel24.setBounds(60, 10, 240, 40);

        homePanel.add(jPanel10);
        jPanel10.setBounds(810, 480, 370, 60);

        jPanel11.setLayout(null);

        jLabel43.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(0, 0, 0));
        jLabel43.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel43.setText("Assets");
        jLabel43.setAlignmentX(931.0F);
        jLabel43.setAlignmentY(64.0F);
        jPanel11.add(jLabel43);
        jLabel43.setBounds(10, 0, 240, 40);

        jLabel44.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(0, 0, 0));
        jLabel44.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel44.setText("3002");
        jLabel44.setAlignmentX(931.0F);
        jLabel44.setAlignmentY(64.0F);
        jPanel11.add(jLabel44);
        jLabel44.setBounds(10, 40, 240, 40);

        homePanel.add(jPanel11);
        jPanel11.setBounds(570, 110, 270, 90);

        jPanel12.setLayout(null);

        jLabel45.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(0, 0, 0));
        jLabel45.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel45.setText("Total: 20202");
        jLabel45.setAlignmentX(931.0F);
        jLabel45.setAlignmentY(64.0F);
        jPanel12.add(jLabel45);
        jLabel45.setBounds(60, 10, 240, 40);

        homePanel.add(jPanel12);
        jPanel12.setBounds(10, 480, 370, 60);

        jPanel13.setLayout(null);

        jLabel46.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(0, 0, 0));
        jLabel46.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel46.setText("Total: 20202");
        jLabel46.setAlignmentX(931.0F);
        jLabel46.setAlignmentY(64.0F);
        jPanel13.add(jLabel46);
        jLabel46.setBounds(60, 10, 240, 40);

        homePanel.add(jPanel13);
        jPanel13.setBounds(410, 480, 370, 60);

        Container.add(homePanel, "card2");

        memberPanel.setBackground(new java.awt.Color(255, 255, 255));
        memberPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                memberPanelMouseReleased(evt);
            }
        });
        memberPanel.setLayout(null);

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable4);

        memberPanel.add(jScrollPane4);
        jScrollPane4.setBounds(10, 70, 1160, 480);

        jButton2.setText("EDIT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        memberPanel.add(jButton2);
        jButton2.setBounds(880, 20, 110, 40);
        memberPanel.add(jTextField1);
        jTextField1.setBounds(150, 20, 250, 40);

        jButton3.setText("FIND");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        memberPanel.add(jButton3);
        jButton3.setBounds(400, 20, 110, 40);

        jButton4.setText("ADD MEMBER");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        memberPanel.add(jButton4);
        jButton4.setBounds(520, 20, 110, 40);

        jButton5.setText("REFRESH");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        memberPanel.add(jButton5);
        jButton5.setBounds(640, 20, 110, 40);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NAME", "ADDRESS" }));
        memberPanel.add(jComboBox1);
        jComboBox1.setBounds(10, 20, 140, 40);

        jButton6.setText("DELETE");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        memberPanel.add(jButton6);
        jButton6.setBounds(760, 20, 110, 40);

        Container.add(memberPanel, "card2");

        accountsPanel.setBackground(new java.awt.Color(255, 255, 255));
        accountsPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                accountsPanelMouseReleased(evt);
            }
        });
        accountsPanel.setLayout(null);
        Container.add(accountsPanel, "card2");

        collectionPanel.setBackground(new java.awt.Color(255, 255, 255));
        collectionPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                collectionPanelMouseReleased(evt);
            }
        });
        collectionPanel.setLayout(null);

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(jTable5);

        collectionPanel.add(jScrollPane5);
        jScrollPane5.setBounds(10, 70, 1160, 480);

        jButton10.setText("REFRESH");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        collectionPanel.add(jButton10);
        jButton10.setBounds(700, 20, 110, 40);

        jButton11.setText("DELETE");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        collectionPanel.add(jButton11);
        jButton11.setBounds(940, 20, 110, 40);

        jButton12.setText("ADD NEW COLLECTION");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        collectionPanel.add(jButton12);
        jButton12.setBounds(520, 20, 170, 40);

        jButton13.setText("FIND");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        collectionPanel.add(jButton13);
        jButton13.setBounds(400, 20, 110, 40);
        collectionPanel.add(jTextField3);
        jTextField3.setBounds(150, 20, 250, 40);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NAME", "ADDRESS" }));
        collectionPanel.add(jComboBox3);
        jComboBox3.setBounds(10, 20, 140, 40);

        jButton30.setText("EDIT");
        jButton30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton30ActionPerformed(evt);
            }
        });
        collectionPanel.add(jButton30);
        jButton30.setBounds(1060, 20, 110, 40);

        jButton26.setText("EDIT");
        jButton26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton26ActionPerformed(evt);
            }
        });
        collectionPanel.add(jButton26);
        jButton26.setBounds(820, 20, 110, 40);

        Container.add(collectionPanel, "card2");

        donationPanel.setBackground(new java.awt.Color(255, 255, 255));
        donationPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                donationPanelMouseReleased(evt);
            }
        });
        donationPanel.setLayout(null);

        jTable6.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane6.setViewportView(jTable6);

        donationPanel.add(jScrollPane6);
        jScrollPane6.setBounds(10, 70, 1160, 480);

        jButton14.setText("EDIT");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        donationPanel.add(jButton14);
        jButton14.setBounds(930, 20, 110, 40);

        jButton15.setText("REFRESH");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        donationPanel.add(jButton15);
        jButton15.setBounds(690, 20, 110, 40);

        jButton16.setText("ADD NEW DONATION");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        donationPanel.add(jButton16);
        jButton16.setBounds(520, 20, 160, 40);

        jButton17.setText("FIND");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        donationPanel.add(jButton17);
        jButton17.setBounds(400, 20, 110, 40);
        donationPanel.add(jTextField4);
        jTextField4.setBounds(150, 20, 250, 40);

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NAME", "ADDRESS" }));
        donationPanel.add(jComboBox4);
        jComboBox4.setBounds(10, 20, 140, 40);

        jButton31.setText("DELETE");
        jButton31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton31ActionPerformed(evt);
            }
        });
        donationPanel.add(jButton31);
        jButton31.setBounds(810, 20, 110, 40);

        Container.add(donationPanel, "card2");

        expensesPanel.setBackground(new java.awt.Color(255, 255, 255));
        expensesPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                expensesPanelMouseReleased(evt);
            }
        });
        expensesPanel.setLayout(null);

        jTable7.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane7.setViewportView(jTable7);

        expensesPanel.add(jScrollPane7);
        jScrollPane7.setBounds(10, 70, 1160, 480);

        jButton18.setText("EDIT");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        expensesPanel.add(jButton18);
        jButton18.setBounds(760, 20, 110, 40);

        jButton19.setText("DELETE");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        expensesPanel.add(jButton19);
        jButton19.setBounds(640, 20, 110, 40);

        jButton20.setText("ADD New");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        expensesPanel.add(jButton20);
        jButton20.setBounds(520, 20, 110, 40);

        jButton21.setText("FIND");
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        expensesPanel.add(jButton21);
        jButton21.setBounds(400, 20, 110, 40);
        expensesPanel.add(jTextField5);
        jTextField5.setBounds(150, 20, 250, 40);

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NAME", "ADDRESS" }));
        expensesPanel.add(jComboBox5);
        jComboBox5.setBounds(10, 20, 140, 40);

        Container.add(expensesPanel, "card2");

        salaryPanel.setBackground(new java.awt.Color(255, 255, 255));
        salaryPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                salaryPanelMouseReleased(evt);
            }
        });
        salaryPanel.setLayout(null);

        jTable8.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane8.setViewportView(jTable8);

        salaryPanel.add(jScrollPane8);
        jScrollPane8.setBounds(10, 70, 1160, 480);

        jButton7.setText("EDIT");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        salaryPanel.add(jButton7);
        jButton7.setBounds(880, 20, 110, 40);
        salaryPanel.add(jTextField2);
        jTextField2.setBounds(150, 20, 250, 40);

        jButton8.setText("FIND");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        salaryPanel.add(jButton8);
        jButton8.setBounds(400, 20, 110, 40);

        jButton9.setText("ADD NEW");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        salaryPanel.add(jButton9);
        jButton9.setBounds(520, 20, 110, 40);

        jButton27.setText("REFRESH");
        jButton27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton27ActionPerformed(evt);
            }
        });
        salaryPanel.add(jButton27);
        jButton27.setBounds(640, 20, 110, 40);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NAME", "ADDRESS" }));
        salaryPanel.add(jComboBox2);
        jComboBox2.setBounds(10, 20, 140, 40);

        jButton28.setText("DELETE");
        jButton28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton28ActionPerformed(evt);
            }
        });
        salaryPanel.add(jButton28);
        jButton28.setBounds(760, 20, 110, 40);

        Container.add(salaryPanel, "card2");

        comitteePanel.setBackground(new java.awt.Color(255, 255, 255));
        comitteePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                comitteePanelMouseReleased(evt);
            }
        });
        comitteePanel.setLayout(null);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dark-landscape-with-bird-flying-1.png"))); // NOI18N
        comitteePanel.add(jLabel12);
        jLabel12.setBounds(0, 0, 1250, 650);

        Container.add(comitteePanel, "card2");

        adminPanel.setBackground(new java.awt.Color(255, 255, 255));
        adminPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                adminPanelMouseReleased(evt);
            }
        });
        adminPanel.setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dark-landscape-with-bird-flying-1.png"))); // NOI18N
        adminPanel.add(jLabel2);
        jLabel2.setBounds(0, 0, 1250, 650);

        Container.add(adminPanel, "card2");

        mainPanel.add(Container);
        Container.setBounds(118, 118, 1250, 650);

        getContentPane().add(mainPanel);
        mainPanel.setBounds(0, 0, 1366, 768);

        setSize(new java.awt.Dimension(1382, 807));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void comitteePanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comitteePanelMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_comitteePanelMouseReleased

    private void salaryPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salaryPanelMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_salaryPanelMouseReleased

    private void expensesPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_expensesPanelMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_expensesPanelMouseReleased

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton18ActionPerformed

    private void donationPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_donationPanelMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_donationPanelMouseReleased

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton14ActionPerformed

    private void collectionPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_collectionPanelMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_collectionPanelMouseReleased

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // actionform
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void accountsPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountsPanelMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_accountsPanelMouseReleased

    private void memberPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_memberPanelMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_memberPanelMouseReleased

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // acttion form:
        ActionPanel f= new ActionPanel();
        f.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void homePanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homePanelMouseReleased
        // TODO add your handling code here:
        if(evt.isPopupTrigger()){
            jPopupMenu1.show(this,evt.getX(),evt.getY());
        }
    }//GEN-LAST:event_homePanelMouseReleased

    private void jLabel11ComponentRemoved(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jLabel11ComponentRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel11ComponentRemoved

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        jLabel57.setText("ADMIN");
        homePanel.setVisible(false);
        memberPanel.setVisible(false);
        accountsPanel.setVisible(false);
        collectionPanel.setVisible(false);
        donationPanel.setVisible(false);
        expensesPanel.setVisible(false);
        salaryPanel.setVisible(false);
        comitteePanel.setVisible(false);
        adminPanel.setVisible(true);
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        jLabel57.setText("COMITTEE");
        homePanel.setVisible(false);
        memberPanel.setVisible(false);
        accountsPanel.setVisible(false);
        collectionPanel.setVisible(false);
        donationPanel.setVisible(false);
        expensesPanel.setVisible(false);
        salaryPanel.setVisible(false);
        comitteePanel.setVisible(true);
        adminPanel.setVisible(false);
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        showNav("Employee:");
        jLabel57.setText("SALARIES");
        homePanel.setVisible(false);
        memberPanel.setVisible(false);
        accountsPanel.setVisible(false);
        collectionPanel.setVisible(false);
        donationPanel.setVisible(false);
        expensesPanel.setVisible(false);
        salaryPanel.setVisible(true);
        comitteePanel.setVisible(false);
        adminPanel.setVisible(false);
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        showNav("Donor:");
        jLabel57.setText("DONATIONS");
        homePanel.setVisible(false);
        memberPanel.setVisible(false);
        accountsPanel.setVisible(false);
        collectionPanel.setVisible(false);
        donationPanel.setVisible(true);
        expensesPanel.setVisible(false);
        salaryPanel.setVisible(false);
        comitteePanel.setVisible(false);
        adminPanel.setVisible(false);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        showNav("Expense:");
        jLabel57.setText("EXPENSES");
        homePanel.setVisible(false);
        memberPanel.setVisible(false);
        accountsPanel.setVisible(false);
        collectionPanel.setVisible(false);
        donationPanel.setVisible(false);
        expensesPanel.setVisible(true);
        salaryPanel.setVisible(false);
        comitteePanel.setVisible(false);
        adminPanel.setVisible(false);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        showNav("Collection:");
        jLabel57.setText("COLLECTIONS");
        homePanel.setVisible(false);
        memberPanel.setVisible(false);
        accountsPanel.setVisible(false);
        collectionPanel.setVisible(true);
        donationPanel.setVisible(false);
        expensesPanel.setVisible(false);
        salaryPanel.setVisible(false);
        comitteePanel.setVisible(false);
        adminPanel.setVisible(false);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        showNav("Member:");
        jLabel57.setText("MEMBERS");
        memberPanel.setVisible(true);
        homePanel.setVisible(false);
        accountsPanel.setVisible(false);
        collectionPanel.setVisible(false);
        donationPanel.setVisible(false);
        expensesPanel.setVisible(false);
        salaryPanel.setVisible(false);
        comitteePanel.setVisible(false);
        adminPanel.setVisible(false);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        // TODO add your handling code here:
        hideNav();
        jLabel57.setText("HOME");
        homePanel.setVisible(true);
        memberPanel.setVisible(false);
        accountsPanel.setVisible(false);
        collectionPanel.setVisible(false);
        donationPanel.setVisible(false);
        expensesPanel.setVisible(false);
        salaryPanel.setVisible(false);
        comitteePanel.setVisible(false);
        adminPanel.setVisible(false);
    }//GEN-LAST:event_jLabel16MouseClicked

    private void jLabel16ComponentRemoved(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jLabel16ComponentRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel16ComponentRemoved

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        jLabel57.setText("ACCOUNTS");
        homePanel.setVisible(false);
        memberPanel.setVisible(false);
        accountsPanel.setVisible(true);
        collectionPanel.setVisible(false);
        donationPanel.setVisible(false);
        expensesPanel.setVisible(false);
        salaryPanel.setVisible(false);
        comitteePanel.setVisible(false);
        adminPanel.setVisible(false);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jButton30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton30ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton30ActionPerformed

    private void jButton31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton31ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton31ActionPerformed

    private void adminPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminPanelMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_adminPanelMouseReleased

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton26ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton26ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton27ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton27ActionPerformed

    private void jButton28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton28ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton28ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton29ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton29ActionPerformed

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        //Log Out:
        this.dispose();
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel16MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseEntered
        // TODO add your handling code here:
         home1.setBackground(new Color(80, 166, 178));
         jLabel16.setForeground(Color.WHITE);
    }//GEN-LAST:event_jLabel16MouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane Container;
    private javax.swing.JPanel SidePanel;
    private javax.swing.JPanel accountsPanel;
    private javax.swing.JPanel adminPanel;
    private javax.swing.JPanel collectionPanel;
    private javax.swing.JPanel comitteePanel;
    private javax.swing.JPanel donationPanel;
    private javax.swing.JPanel expensesPanel;
    private javax.swing.JPanel home;
    private javax.swing.JPanel home1;
    private javax.swing.JPanel home2;
    private javax.swing.JPanel home3;
    private javax.swing.JPanel home4;
    private javax.swing.JPanel home5;
    private javax.swing.JPanel home6;
    private javax.swing.JPanel home7;
    private javax.swing.JPanel home8;
    private javax.swing.JPanel home9;
    private javax.swing.JPanel homePanel;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable5;
    private javax.swing.JTable jTable6;
    private javax.swing.JTable jTable7;
    private javax.swing.JTable jTable8;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel memberPanel;
    private javax.swing.JMenu menu1;
    private javax.swing.JMenu menu2;
    private javax.swing.JPanel salaryPanel;
    private javax.swing.JMenuItem test3;
    private javax.swing.JPanel topPanel;
    // End of variables declaration//GEN-END:variables
}
